var data = [
    '{"long": "Erebos", "short": "Erebos", "link": "geography.html#Erebos"}',
    '{"long": "Orestes", "short": "Orestes", "link": "geography.html#Orestes"}',
    '{"long": "Piskus", "short": "Piskus", "link": "geography.html#Piskus"}',
    '{"long": "Kestren", "short": "Kestren", "link": "geography.html#Kestren"}',
    '{"long": "Nardone", "short": "Nardone", "link": "geography.html#Nardone"}',
    '{"long": "Isles of Constros", "short": "Isles of Constros", "link": "geography.html#Isles of Constros"}',
    '{"long": "The Cloud", "short": "Cloud", "link": "geography.html#The Cloud"}',
    '{"long": "Calatios (Erebos)", "short": "Calatios", "link": "politics.html#Calatios (Erebos)"}',
    '{"long": "Arrigo (Erebos)", "short": "Arrigo", "link": "politics.html#Arrigo (Erebos)"}',
    '{"long": "Galima (Erebos)", "short": "Galima", "link": "politics.html#Galima (Erebos)"}',
    '{"long": "Bulus (Erebos)", "short": "Bulus", "link": "politics.html#Bulus (Erebos)"}',
    '{"long": "Drusque (Erebos)", "short": "Drusque", "link": "politics.html#Drusque (Erebos)"}',
    '{"long": "Kishori (Erebos)", "short": "Kishori", "link": "politics.html#Kishori (Erebos)"}',
    '{"long": "Kasseiopia (Erebos)", "short": "Kasseiopia", "link": "politics.html#Kasseiopia (Erebos)"}',
    '{"long": "Tiryns (Erebos)", "short": "Tiryns", "link": "politics.html#Tiryns (Erebos)"}',
    '{"long": "Demetriades (Erebos)", "short": "Demetriades", "link": "politics.html#Demetriades (Erebos)"}',
    '{"long": "New Nardone (Erebos)", "short": "New Nardone", "link": "politics.html#New Nardone (Erebos)"}',
    '{"long": "Vasileios (Erebos)", "short": "Vasileios", "link": "politics.html#Vasileios (Erebos)"}',
    '{"long": "Megaera (Orestes)", "short": "Megaera", "link": "politics.html#Megaera (Orestes)"}',
    '{"long": "Kalistos (Orestes)", "short": "Kalistos", "link": "politics.html#Kalistos (Orestes)"}',
    '{"long": "Firbolg Villages (Piskus)", "short": "Firbolg Villages", "link": "politics.html#Firbolg Villages (Piskus)"}',
    '{"long": "Tortle Villages (Piskus)", "short": "Tortle Villages", "link": "politics.html#Tortle Villages (Piskus)"}',
    '{"long": "The Kingdom of Lizael (Piskus)", "short": "Kingdom of Lizael", "link": "politics.html#The Kingdom of Lizael (Piskus)"}',
    '{"long": "The Piskus Colonies (Piskus)", "short": "Piskus Colonies", "link": "politics.html#The Piskus Colonies (Piskus)"}',
    '{"long": "Calatios", "short": "Calatios", "link": "politics.html#Calatios"}',
    '{"long": "Kishori", "short": "Kishori", "link": "politics.html#Kishori"}',
    '{"long": "Arrigo", "short": "Arrigo", "link": "politics.html#Arrigo"}',
    '{"long": "The Giant Caves (Kestren)", "short": "Giant Caves", "link": "politics.html#The Giant Caves (Kestren)"}',
    '{"long": "The Goliath Nomads (Kestren)", "short": "Goliath Nomads", "link": "politics.html#The Goliath Nomads (Kestren)"}',
    '{"long": "The Orcish Nomads (Kestren)", "short": "Orcish Nomads", "link": "politics.html#The Orcish Nomads (Kestren)"}',
    '{"long": "The Aarakocra Peaks (Kestren)", "short": "Aarakocra Peaks", "link": "politics.html#The Aarakocra Peaks (Kestren)"}',
    '{"long": "The Kenku Valleys (Kestren)", "short": "Kenku Valleys", "link": "politics.html#The Kenku Valleys (Kestren)"}',
    '{"long": "Haven Town (Kestren)", "short": "Haven Town", "link": "politics.html#Haven Town (Kestren)"}',
    '{"long": "Ngana (Constros)", "short": "Ngana", "link": "politics.html#Ngana (Constros)"}',
    '{"long": "Gemelo [hem-ello] (Constros)", "short": "Gemelo [hem-ello]", "link": "politics.html#Gemelo [hem-ello] (Constros)"}',
    '{"long": "Marcella (Constros)", "short": "Marcella", "link": "politics.html#Marcella (Constros)"}',
    '{"long": "New Kishori, Aleki (Constros)", "short": "New Kishori, Aleki", "link": "politics.html#New Kishori, Aleki (Constros)"}',
    '{"long": "Human", "short": "Human", "link": "races.html#Human"}',
    '{"long": "Elf", "short": "Elf", "link": "races.html#Elf"}',
    '{"long": "Half-Elf (Khoravar)", "short": "Half-Elf", "link": "races.html#Half-Elf (Khoravar)"}',
    '{"long": "Changeling (Khoravar)", "short": "Changeling", "link": "races.html#Changeling (Khoravar)"}',
    '{"long": "Dwarf", "short": "Dwarf", "link": "races.html#Dwarf"}',
    '{"long": "Tabaxi", "short": "Tabaxi", "link": "races.html#Tabaxi"}',
    '{"long": "Goliath", "short": "Goliath", "link": "races.html#Goliath"}',
    '{"long": "Orc", "short": "Orc", "link": "races.html#Orc"}',
    '{"long": "Half-Orc", "short": "Half-Orc", "link": "races.html#Half-Orc"}',
    '{"long": "Aarakocra", "short": "Aarakocra", "link": "races.html#Aarakocra"}',
    '{"long": "Kenku", "short": "Kenku", "link": "races.html#Kenku"}',
    '{"long": "Kobold", "short": "Kobold", "link": "races.html#Kobold"}',
    '{"long": "Tortle", "short": "Tortle", "link": "races.html#Tortle"}',
    '{"long": "Hobgoblin", "short": "Hobgoblin", "link": "races.html#Hobgoblin"}',
    '{"long": "Goblin", "short": "Goblin", "link": "races.html#Goblin"}',
    '{"long": "Bugbear", "short": "Bugbear", "link": "races.html#Bugbear"}',
    '{"long": "Shifter", "short": "Shifter", "link": "races.html#Shifter"}',
    '{"long": "Loxodon", "short": "Loxodon", "link": "races.html#Loxodon"}',
    '{"long": "Centaur", "short": "Centaur", "link": "races.html#Centaur"}',
    '{"long": "Minotaur", "short": "Minotaur", "link": "races.html#Minotaur"}',
    '{"long": "Drow", "short": "Drow", "link": "races.html#Drow"}',
    '{"long": "Tiefling", "short": "Tiefling", "link": "races.html#Tiefling"}',
    '{"long": "Aasimar", "short": "Aasimar", "link": "races.html#Aasimar"}',
    '{"long": "Firbolg", "short": "Firbolg", "link": "races.html#Firbolg"}',
    '{"long": "Lizardfolk", "short": "Lizardfolk", "link": "races.html#Lizardfolk"}',
    '{"long": "Triton", "short": "Triton", "link": "races.html#Triton"}',
    '{"long": "Kalashtar", "short": "Kalashtar", "link": "races.html#Kalashtar"}',
    '{"long": "Warforged", "short": "Warforged", "link": "races.html#Warforged"}',
    '{"long": "Dragonborn", "short": "Dragonborn", "link": "races.html#Dragonborn"}',
    '{"long": "Gnome", "short": "Gnome", "link": "races.html#Gnome"}',
    '{"long": "Halfling", "short": "Halfling", "link": "races.html#Halfling"}',
    '{"long": "Genasi", "short": "Genasi", "link": "races.html#Genasi"}',
    '{"long": "Vedalken", "short": "Vedalken", "link": "races.html#Vedalken"}',
    '{"long": "Satyr", "short": "Satyr", "link": "races.html#Satyr"}',
    '{"long": "Simic Hybrid", "short": "Simic Hybrid", "link": "races.html#Simic Hybrid"}',
    '{"long": "The Major Gods", "short": "Major Gods", "link": "religion.html#The Major Gods"}',
    '{"long": "Volkmer", "short": "Volkmer", "link": "religion.html#Volkmer"}',
    '{"long": "Tiya", "short": "Tiya", "link": "religion.html#Tiya"}',
    '{"long": "Pyrin", "short": "Pyrin", "link": "religion.html#Pyrin"}',
    '{"long": "Shaylar\u00e8", "short": "Shaylar\u00e8", "link": "religion.html#Shaylar\u00e8"}',
    '{"long": "Chyrillus", "short": "Chyrillus", "link": "religion.html#Chyrillus"}',
    '{"long": "Einar", "short": "Einar", "link": "religion.html#Einar"}',
    '{"long": "Ayla", "short": "Ayla", "link": "religion.html#Ayla"}',
    '{"long": "Kor", "short": "Kor", "link": "religion.html#Kor"}',
    '{"long": "Archeptolemus", "short": "Archeptolemus", "link": "religion.html#Archeptolemus"}',
    '{"long": "Prothous", "short": "Prothous", "link": "religion.html#Prothous"}',
    '{"long": "Adour", "short": "Adour", "link": "religion.html#Adour"}',
    '{"long": "Nevaeh", "short": "Nevaeh", "link": "religion.html#Nevaeh"}',
    '{"long": "Zethos", "short": "Zethos", "link": "religion.html#Zethos"}',
    '{"long": "The Minor Gods", "short": "Minor Gods", "link": "religion.html#The Minor Gods"}',
    '{"long": "Nechtu", "short": "Nechtu", "link": "religion.html#Nechtu"}',
    '{"long": "Loriana", "short": "Loriana", "link": "religion.html#Loriana"}',
    '{"long": "Iosepha", "short": "Iosepha", "link": "religion.html#Iosepha"}',
    '{"long": "Callicles", "short": "Callicles", "link": "religion.html#Callicles"}',
    '{"long": "Gulkishar", "short": "Gulkishar", "link": "religion.html#Gulkishar"}',
    '{"long": "Av\u00e8", "short": "Av\u00e8", "link": "religion.html#Av\u00e8"}',
    '{"long": "Golmala", "short": "Golmala", "link": "religion.html#Golmala"}',
    '{"long": "Quiro", "short": "Quiro", "link": "religion.html#Quiro"}',
    '{"long": "Thov\u00e8", "short": "Thov\u00e8", "link": "religion.html#Thov\u00e8"}',
    '{"long": "Hurmut", "short": "Hurmut", "link": "religion.html#Hurmut"}',
    '{"long": "Nthanda", "short": "Nthanda", "link": "religion.html#Nthanda"}',
    '{"long": "Sorcerous Houses", "short": "Sorcerous Houses", "link": "religion.html#Sorcerous Houses"}',
    '{"long": "House of Volkmer", "short": "House of Volkmer", "link": "religion.html#House of Volkmer"}',
    '{"long": "House of Pyrin", "short": "House of Pyrin", "link": "religion.html#House of Pyrin"}',
    '{"long": "House of Kor", "short": "House of Kor", "link": "religion.html#House of Kor"}',
    '{"long": "House of Nevaeh", "short": "House of Nevaeh", "link": "religion.html#House of Nevaeh"}',
    '{"long": "House of Adour", "short": "House of Adour", "link": "religion.html#House of Adour"}',
    '{"long": "House of Shaylar\u00e8", "short": "House of Shaylar\u00e8", "link": "religion.html#House of Shaylar\u00e8"}',
    '{"long": "House of Chyrillus", "short": "House of Chyrillus", "link": "religion.html#House of Chyrillus"}',
    '{"long": "Fiends", "short": "Fiends", "link": "monsters.html#Fiends"}',
    '{"long": "Aberrations", "short": "Aberrations", "link": "monsters.html#Aberrations"}',
    '{"long": "Beasts", "short": "Beasts", "link": "monsters.html#Beasts"}',
    '{"long": "Celestials", "short": "Celestials", "link": "monsters.html#Celestials"}',
    '{"long": "Monstrosities", "short": "Monstrosities", "link": "monsters.html#Monstrosities"}',
    '{"long": "Plants", "short": "Plants", "link": "monsters.html#Plants"}',
    '{"long": "Fey", "short": "Fey", "link": "monsters.html#Fey"}',
    '{"long": "Undead", "short": "Undead", "link": "monsters.html#Undead"}',
    '{"long": "Constructs", "short": "Constructs", "link": "monsters.html#Constructs"}',
    '{"long": "Elementals", "short": "Elementals", "link": "monsters.html#Elementals"}',
    '{"long": "Unique Monsters", "short": "Unique Monsters", "link": "monsters.html#Unique Monsters"}',
    '{"long": "Elementally Touched Areas", "short": "Elementally Touched Areas", "link": "cosmology.html#Elementally Touched Areas"}',
    '{"long": "The Feywild", "short": "Feywild", "link": "cosmology.html#The Feywild"}',
    '{"long": "The Shadowfell", "short": "Shadowfell", "link": "cosmology.html#The Shadowfell"}',
    '{"long": "The Spirit Plane", "short": "Spirit Plane", "link": "cosmology.html#The Spirit Plane"}',
    '{"long": "Celestia", "short": "Celestia", "link": "cosmology.html#Celestia"}',
    '{"long": "The Ethereal Plane", "short": "Ethereal Plane", "link": "cosmology.html#The Ethereal Plane"}'
]

function search() {
    let input = document.getElementById('searchbar').value.toLowerCase();

    for (i = 0; i < data.length; i++) {
        var term = JSON.parse(data[i]);
        // if (!term[i].long.toLowerCase().includes(input)) {
        //    x[i].style.display="none";
        if (term.short.toLowerCase() == input.toLowerCase()) {
            window.location.href = term.link;
        }
    }
}
