function search() {
    let input = document.getElementById('searchbar').value.toLowerCase();

    for (i = 0; i < data.length; i++) {
        var term = JSON.parse(data[i]);
        if (term.short.toLowerCase() == input || term.long.toLowerCase() == input) {
            window.location.href = term.link;
        }
    }
}

var data = [
	'{"long": "Erebos", "short": "Erebos", "link": "geography.html#Erebos"}',
	'{"long": "Orestes", "short": "Orestes", "link": "geography.html#Orestes"}',
	'{"long": "Piskus", "short": "Piskus", "link": "geography.html#Piskus"}',
	'{"long": "Kestren", "short": "Kestren", "link": "geography.html#Kestren"}',
	'{"long": "Nardone", "short": "Nardone", "link": "geography.html#Nardone"}',
	'{"long": "Isles of Constros", "short": "Isles of Constros", "link": "geography.html#Isles of Constros"}',
	'{"long": "The Cloud", "short": "Cloud", "link": "geography.html#The Cloud"}',
	'{"long": "Calatios (Erebos)", "short": "Calatios", "link": "politics.html#Calatios (Erebos)"}',
	'{"long": "Arrigo (Erebos)", "short": "Arrigo", "link": "politics.html#Arrigo (Erebos)"}',
	'{"long": "Galima (Erebos)", "short": "Galima", "link": "politics.html#Galima (Erebos)"}',
	'{"long": "Bulus (Erebos)", "short": "Bulus", "link": "politics.html#Bulus (Erebos)"}',
	'{"long": "Drusque (Erebos)", "short": "Drusque", "link": "politics.html#Drusque (Erebos)"}',
	'{"long": "Kishori (Erebos)", "short": "Kishori", "link": "politics.html#Kishori (Erebos)"}',
	'{"long": "Kasseiopia (Erebos)", "short": "Kasseiopia", "link": "politics.html#Kasseiopia (Erebos)"}',
	'{"long": "Tiryns (Erebos)", "short": "Tiryns", "link": "politics.html#Tiryns (Erebos)"}',
	'{"long": "Demetriades (Erebos)", "short": "Demetriades", "link": "politics.html#Demetriades (Erebos)"}',
	'{"long": "New Nardone (Erebos)", "short": "New Nardone", "link": "politics.html#New Nardone (Erebos)"}',
	'{"long": "Vasileios (Erebos)", "short": "Vasileios", "link": "politics.html#Vasileios (Erebos)"}',
	'{"long": "Megaera (Orestes)", "short": "Megaera", "link": "politics.html#Megaera (Orestes)"}',
	'{"long": "Kalistos (Orestes)", "short": "Kalistos", "link": "politics.html#Kalistos (Orestes)"}',
	'{"long": "Firbolg Villages (Piskus)", "short": "Firbolg Villages", "link": "politics.html#Firbolg Villages (Piskus)"}',
	'{"long": "Tortle Villages (Piskus)", "short": "Tortle Villages", "link": "politics.html#Tortle Villages (Piskus)"}',
	'{"long": "The Kingdom of Lizael (Piskus)", "short": "Kingdom of Lizael", "link": "politics.html#The Kingdom of Lizael (Piskus)"}',
	'{"long": "The Piskus Colonies (Piskus)", "short": "Piskus Colonies", "link": "politics.html#The Piskus Colonies (Piskus)"}',
	'{"long": "Calatios", "short": "Calatios", "link": "politics.html#Calatios"}',
	'{"long": "Kishori", "short": "Kishori", "link": "politics.html#Kishori"}',
	'{"long": "Arrigo", "short": "Arrigo", "link": "politics.html#Arrigo"}',
	'{"long": "The Giant Caves (Kestren)", "short": "Giant Caves", "link": "politics.html#The Giant Caves (Kestren)"}',
	'{"long": "The Goliath Nomads (Kestren)", "short": "Goliath Nomads", "link": "politics.html#The Goliath Nomads (Kestren)"}',
	'{"long": "The Orcish Nomads (Kestren)", "short": "Orcish Nomads", "link": "politics.html#The Orcish Nomads (Kestren)"}',
	'{"long": "The Aarakocra Peaks (Kestren)", "short": "Aarakocra Peaks", "link": "politics.html#The Aarakocra Peaks (Kestren)"}',
	'{"long": "The Kenku Valleys (Kestren)", "short": "Kenku Valleys", "link": "politics.html#The Kenku Valleys (Kestren)"}',
	'{"long": "Haven Town (Kestren)", "short": "Haven Town", "link": "politics.html#Haven Town (Kestren)"}',
	'{"long": "Ngana (Constros)", "short": "Ngana", "link": "politics.html#Ngana (Constros)"}',
	'{"long": "Gemelo [hem-ello] (Constros)", "short": "Gemelo [hem-ello]", "link": "politics.html#Gemelo [hem-ello] (Constros)"}',
	'{"long": "Marcella (Constros)", "short": "Marcella", "link": "politics.html#Marcella (Constros)"}',
	'{"long": "New Kishori, Aleki (Constros)", "short": "New Kishori, Aleki", "link": "politics.html#New Kishori, Aleki (Constros)"}',
	'{"long": "Human", "short": "Human", "link": "races.html#Human"}',
	'{"long": "Elf", "short": "Elf", "link": "races.html#Elf"}',
	'{"long": "Half-Elf (Khoravar)", "short": "Half-Elf", "link": "races.html#Half-Elf (Khoravar)"}',
	'{"long": "Changeling (Khoravar)", "short": "Changeling", "link": "races.html#Changeling (Khoravar)"}',
	'{"long": "Dwarf", "short": "Dwarf", "link": "races.html#Dwarf"}',
	'{"long": "Tabaxi", "short": "Tabaxi", "link": "races.html#Tabaxi"}',
	'{"long": "Goliath", "short": "Goliath", "link": "races.html#Goliath"}',
	'{"long": "Orc", "short": "Orc", "link": "races.html#Orc"}',
	'{"long": "Half-Orc", "short": "Half-Orc", "link": "races.html#Half-Orc"}',
	'{"long": "Aarakocra", "short": "Aarakocra", "link": "races.html#Aarakocra"}',
	'{"long": "Kenku", "short": "Kenku", "link": "races.html#Kenku"}',
	'{"long": "Kobold", "short": "Kobold", "link": "races.html#Kobold"}',
	'{"long": "Tortle", "short": "Tortle", "link": "races.html#Tortle"}',
	'{"long": "Hobgoblin", "short": "Hobgoblin", "link": "races.html#Hobgoblin"}',
	'{"long": "Goblin", "short": "Goblin", "link": "races.html#Goblin"}',
	'{"long": "Bugbear", "short": "Bugbear", "link": "races.html#Bugbear"}',
	'{"long": "Shifter", "short": "Shifter", "link": "races.html#Shifter"}',
	'{"long": "Loxodon", "short": "Loxodon", "link": "races.html#Loxodon"}',
	'{"long": "Centaur", "short": "Centaur", "link": "races.html#Centaur"}',
	'{"long": "Minotaur", "short": "Minotaur", "link": "races.html#Minotaur"}',
	'{"long": "Drow", "short": "Drow", "link": "races.html#Drow"}',
	'{"long": "Tiefling", "short": "Tiefling", "link": "races.html#Tiefling"}',
	'{"long": "Aasimar", "short": "Aasimar", "link": "races.html#Aasimar"}',
	'{"long": "Firbolg", "short": "Firbolg", "link": "races.html#Firbolg"}',
	'{"long": "Lizardfolk", "short": "Lizardfolk", "link": "races.html#Lizardfolk"}',
	'{"long": "Triton", "short": "Triton", "link": "races.html#Triton"}',
	'{"long": "Kalashtar", "short": "Kalashtar", "link": "races.html#Kalashtar"}',
	'{"long": "Warforged", "short": "Warforged", "link": "races.html#Warforged"}',
	'{"long": "Dragonborn", "short": "Dragonborn", "link": "races.html#Dragonborn"}',
	'{"long": "Gnome", "short": "Gnome", "link": "races.html#Gnome"}',
	'{"long": "Halfling", "short": "Halfling", "link": "races.html#Halfling"}',
	'{"long": "Genasi", "short": "Genasi", "link": "races.html#Genasi"}',
	'{"long": "Vedalken", "short": "Vedalken", "link": "races.html#Vedalken"}',
	'{"long": "Satyr", "short": "Satyr", "link": "races.html#Satyr"}',
	'{"long": "Simic Hybrid", "short": "Simic Hybrid", "link": "races.html#Simic Hybrid"}',
	'{"long": "Giant", "short": "Giant", "link": "races.html#Giant"}',
	'{"long": "The Major Gods", "short": "Major Gods", "link": "religion.html#The Major Gods"}',
	'{"long": "Volkmer", "short": "Volkmer", "link": "religion.html#Volkmer"}',
	'{"long": "Tiya", "short": "Tiya", "link": "religion.html#Tiya"}',
	'{"long": "Pyrin", "short": "Pyrin", "link": "religion.html#Pyrin"}',
	'{"long": "Shaylare", "short": "Shaylare", "link": "religion.html#Shaylare"}',
	'{"long": "Chyrillus", "short": "Chyrillus", "link": "religion.html#Chyrillus"}',
	'{"long": "Einar", "short": "Einar", "link": "religion.html#Einar"}',
	'{"long": "Ayla", "short": "Ayla", "link": "religion.html#Ayla"}',
	'{"long": "Kor", "short": "Kor", "link": "religion.html#Kor"}',
	'{"long": "Archeptolemus", "short": "Archeptolemus", "link": "religion.html#Archeptolemus"}',
	'{"long": "Prothous", "short": "Prothous", "link": "religion.html#Prothous"}',
	'{"long": "Adour", "short": "Adour", "link": "religion.html#Adour"}',
	'{"long": "Nevaeh", "short": "Nevaeh", "link": "religion.html#Nevaeh"}',
	'{"long": "Zethos", "short": "Zethos", "link": "religion.html#Zethos"}',
	'{"long": "The Minor Gods", "short": "Minor Gods", "link": "religion.html#The Minor Gods"}',
	'{"long": "Nechtu", "short": "Nechtu", "link": "religion.html#Nechtu"}',
	'{"long": "Loriana", "short": "Loriana", "link": "religion.html#Loriana"}',
	'{"long": "Iosepha", "short": "Iosepha", "link": "religion.html#Iosepha"}',
	'{"long": "Callicles", "short": "Callicles", "link": "religion.html#Callicles"}',
	'{"long": "Gulkishar", "short": "Gulkishar", "link": "religion.html#Gulkishar"}',
	'{"long": "Ave", "short": "Ave", "link": "religion.html#Ave"}',
	'{"long": "Golmala", "short": "Golmala", "link": "religion.html#Golmala"}',
	'{"long": "Quiro", "short": "Quiro", "link": "religion.html#Quiro"}',
	'{"long": "Thove", "short": "Thove", "link": "religion.html#Thove"}',
	'{"long": "Hurmut", "short": "Hurmut", "link": "religion.html#Hurmut"}',
	'{"long": "Nthanda", "short": "Nthanda", "link": "religion.html#Nthanda"}',
	'{"long": "Sorcerous Houses", "short": "Sorcerous Houses", "link": "religion.html#Sorcerous Houses"}',
	'{"long": "House of Volkmer", "short": "House of Volkmer", "link": "religion.html#House of Volkmer"}',
	'{"long": "House of Pyrin", "short": "House of Pyrin", "link": "religion.html#House of Pyrin"}',
	'{"long": "House of Kor", "short": "House of Kor", "link": "religion.html#House of Kor"}',
	'{"long": "House of Nevaeh", "short": "House of Nevaeh", "link": "religion.html#House of Nevaeh"}',
	'{"long": "House of Adour", "short": "House of Adour", "link": "religion.html#House of Adour"}',
	'{"long": "House of Shaylare", "short": "House of Shaylare", "link": "religion.html#House of Shaylare"}',
	'{"long": "House of Chyrillus", "short": "House of Chyrillus", "link": "religion.html#House of Chyrillus"}',
	'{"long": "Fiends", "short": "Fiends", "link": "monsters.html#Fiends"}',
	'{"long": "Aberrations", "short": "Aberrations", "link": "monsters.html#Aberrations"}',
	'{"long": "Beasts", "short": "Beasts", "link": "monsters.html#Beasts"}',
	'{"long": "Celestials", "short": "Celestials", "link": "monsters.html#Celestials"}',
	'{"long": "Monstrosities", "short": "Monstrosities", "link": "monsters.html#Monstrosities"}',
	'{"long": "Plants", "short": "Plants", "link": "monsters.html#Plants"}',
	'{"long": "Fey", "short": "Fey", "link": "monsters.html#Fey"}',
	'{"long": "Undead", "short": "Undead", "link": "monsters.html#Undead"}',
	'{"long": "Constructs", "short": "Constructs", "link": "monsters.html#Constructs"}',
	'{"long": "Elementals", "short": "Elementals", "link": "monsters.html#Elementals"}',
	'{"long": "Unique Monsters", "short": "Unique Monsters", "link": "monsters.html#Unique Monsters"}',
	'{"long": "Elementally Touched Areas", "short": "Elementally Touched Areas", "link": "cosmology.html#Elementally Touched Areas"}',
	'{"long": "The Feywild", "short": "Feywild", "link": "cosmology.html#The Feywild"}',
	'{"long": "The Shadowfell", "short": "Shadowfell", "link": "cosmology.html#The Shadowfell"}',
	'{"long": "The Spirit Plane", "short": "Spirit Plane", "link": "cosmology.html#The Spirit Plane"}',
	'{"long": "Celestia", "short": "Celestia", "link": "cosmology.html#Celestia"}',
	'{"long": "The Ethereal Plane", "short": "Ethereal Plane", "link": "cosmology.html#The Ethereal Plane"}',
	'{"long": "The Material Plane", "short": "Material Plane", "link": "cosmology.html#The Material Plane"}',
	'{"long": "Blasting Chime", "short": "Blasting Chime", "link": "items.html#Blasting Chime"}',
	'{"long": "Behemoth Belt", "short": "Behemoth Belt", "link": "items.html#Behemoth Belt"}',
	'{"long": "Tracker Mask", "short": "Tracker Mask", "link": "items.html#Tracker Mask"}',
	'{"long": "Goodberry Wine", "short": "Goodberry Wine", "link": "items.html#Goodberry Wine"}',
	'{"long": "Balor\u2019s Power Eye", "short": "Balor\u2019s Power Eye", "link": "items.html#Balor\u2019s Power Eye"}',
	'{"long": "Gun", "short": "Gun", "link": "items.html#Gun"}',
	'{"long": "Bow of Piercing", "short": "Bow of Piercing", "link": "items.html#Bow of Piercing"}',
	'{"long": "Teddy Bear of Encouragement", "short": "Teddy Bear of Encouragement", "link": "items.html#Teddy Bear of Encouragement"}',
	'{"long": "Cat\u2019s Paws", "short": "Cat\u2019s Paws", "link": "items.html#Cat\u2019s Paws"}',
	'{"long": "Throwing Knife of Distance", "short": "Throwing Knife of Distance", "link": "items.html#Throwing Knife of Distance"}',
	'{"long": "Ambrosia", "short": "Ambrosia", "link": "items.html#Ambrosia"}',
	'{"long": "Frozen Flower", "short": "Frozen Flower", "link": "items.html#Frozen Flower"}',
	'{"long": "Ring of Armor Conjuration", "short": "Ring of Armor Conjuration", "link": "items.html#Ring of Armor Conjuration"}',
	'{"long": "Spartan Boots", "short": "Spartan Boots", "link": "items.html#Spartan Boots"}',
	'{"long": "Steps of the Wind", "short": "Steps of the Wind", "link": "items.html#Steps of the Wind"}',
	'{"long": "Amulet of Nimble Escape", "short": "Amulet of Nimble Escape", "link": "items.html#Amulet of Nimble Escape"}',
	'{"long": "A Familiar Totem", "short": "Familiar Totem", "link": "items.html#A Familiar Totem"}',
	'{"long": "Time Freeze Pouch", "short": "Time Freeze Pouch", "link": "items.html#Time Freeze Pouch"}',
	'{"long": "Skulker Bow", "short": "Skulker Bow", "link": "items.html#Skulker Bow"}',
	'{"long": "Firestarter Gloves", "short": "Firestarter Gloves", "link": "items.html#Firestarter Gloves"}',
	'{"long": "Ice Sculptor Gloves", "short": "Ice Sculptor Gloves", "link": "items.html#Ice Sculptor Gloves"}',
	'{"long": "Handyman\u2019s Hammer", "short": "Handyman\u2019s Hammer", "link": "items.html#Handyman\u2019s Hammer"}',
	'{"long": "Narrating Storybook", "short": "Narrating Storybook", "link": "items.html#Narrating Storybook"}',
	'{"long": "RPD", "short": "RPD", "link": "items.html#RPD"}',
	'{"long": "Flame Dust", "short": "Flame Dust", "link": "items.html#Flame Dust"}',
	'{"long": "Temperate Cloak", "short": "Temperate Cloak", "link": "items.html#Temperate Cloak"}',
	'{"long": "Pen of Preparation", "short": "Pen of Preparation", "link": "items.html#Pen of Preparation"}',
	'{"long": "Wand of Household Magic", "short": "Wand of Household Magic", "link": "items.html#Wand of Household Magic"}',
	'{"long": "Shield of Repercussion", "short": "Shield of Repercussion", "link": "items.html#Shield of Repercussion"}',
	'{"long": "Armor of Inversion", "short": "Armor of Inversion", "link": "items.html#Armor of Inversion"}',
	'{"long": "Phalanx Shield", "short": "Phalanx Shield", "link": "items.html#Phalanx Shield"}',
	'{"long": "Deft Bow", "short": "Deft Bow", "link": "items.html#Deft Bow"}',
	'{"long": "Gravity Blade", "short": "Gravity Blade", "link": "items.html#Gravity Blade"}',
	'{"long": "Alter Gravity.", "short": "Alter Gravity.", "link": "items.html#Alter Gravity."}',
	'{"long": "Siege Breaker.", "short": "Siege Breaker.", "link": "items.html#Siege Breaker."}',
	'{"long": "Gravekeeper\u2019s Tools:", "short": "Gravekeeper\u2019s Tools:", "link": "items.html#Gravekeeper\u2019s Tools:"}',
	'{"long": "Gravekeeper\u2019s Spade", "short": "Gravekeeper\u2019s Spade", "link": "items.html#Gravekeeper\u2019s Spade"}',
	'{"long": "Gravekeeper Synergy.", "short": "Gravekeeper Synergy.", "link": "items.html#Gravekeeper Synergy."}',
	'{"long": "<em>Chain of the Gravekeeper</em>", "short": "<em>Chain of the Gravekeeper</em>", "link": "items.html#<em>Chain of the Gravekeeper</em>"}',
	'{"long": "Gravekeeper Synergy.", "short": "Gravekeeper Synergy.", "link": "items.html#Gravekeeper Synergy."}',
	'{"long": "Coat of the Gravekeeper", "short": "Coat of the Gravekeeper", "link": "items.html#Coat of the Gravekeeper"}',
	'{"long": "Gravekeeper Synergy.", "short": "Gravekeeper Synergy.", "link": "items.html#Gravekeeper Synergy."}',
	'{"long": "Momentary Strength Bandanna", "short": "Momentary Strength Bandanna", "link": "items.html#Momentary Strength Bandanna"}',
	'{"long": "Spatial Pocket Ring", "short": "Spatial Pocket Ring", "link": "items.html#Spatial Pocket Ring"}',
	'{"long": "Discerning Eye", "short": "Discerning Eye", "link": "items.html#Discerning Eye"}',
	'{"long": "Venusdonoa", "short": "Venusdonoa", "link": "items.html#Venusdonoa"}',
	'{"long": "Random Properties.", "short": "Random Properties.", "link": "items.html#Random Properties."}',
	'{"long": "Spells.", "short": "Spells.", "link": "items.html#Spells."}',
	'{"long": "Conflicting Magic.", "short": "Conflicting Magic.", "link": "items.html#Conflicting Magic."}',
	'{"long": "Destroying the Sword.", "short": "Destroying the Sword.", "link": "items.html#Destroying the Sword."}',
	'{"long": "Evosferrum", "short": "Evosferrum", "link": "items.html#Evosferrum"}',
	'{"long": "Random Properties.", "short": "Random Properties.", "link": "items.html#Random Properties."}',
	'{"long": "Spells.", "short": "Spells.", "link": "items.html#Spells."}',
	'{"long": "Conflicting Magic.", "short": "Conflicting Magic.", "link": "items.html#Conflicting Magic."}',
	'{"long": "Destroying the Sword.", "short": "Destroying the Sword.", "link": "items.html#Destroying the Sword."}',
	'{"long": "The Poisoner\u2019s Pillbox", "short": "Poisoner\u2019s Pillbox", "link": "items.html#The Poisoner\u2019s Pillbox"}',
	'{"long": "Flamberge", "short": "Flamberge", "link": "items.html#Flamberge"}',
	'{"long": "Malachite", "short": "Malachite", "link": "items.html#Malachite"}',
	'{"long": "The Stake Pusher", "short": "Stake Pusher", "link": "items.html#The Stake Pusher"}',
	'{"long": "Cloak of Wandering", "short": "Cloak of Wandering", "link": "items.html#Cloak of Wandering"}',
	'{"long": "Scholar\u2019s Notebook", "short": "Scholar\u2019s Notebook", "link": "items.html#Scholar\u2019s Notebook"}',
	'{"long": "Woodcutter\u2019s Axe", "short": "Woodcutter\u2019s Axe", "link": "items.html#Woodcutter\u2019s Axe"}',
	'{"long": "The Bowstaff", "short": "Bowstaff", "link": "items.html#The Bowstaff"}',
	'{"long": "Ring of Maneuverability", "short": "Ring of Maneuverability", "link": "items.html#Ring of Maneuverability"}',
	'{"long": "Magical Grenade (Blank)", "short": "Magical Grenade", "link": "items.html#Magical Grenade (Blank)"}',
	'{"long": "Magical Grenade (Filled)", "short": "Magical Grenade", "link": "items.html#Magical Grenade (Filled)"}',
	'{"long": "Magic Eater\u2019s Mask", "short": "Magic Eater\u2019s Mask", "link": "items.html#Magic Eater\u2019s Mask"}',
	'{"long": "Symbiotic Nature.", "short": "Symbiotic Nature.", "link": "items.html#Symbiotic Nature."}',
	'{"long": "Protective Chain Collar", "short": "Protective Chain Collar", "link": "items.html#Protective Chain Collar"}',
	'{"long": "Chromatic Anklet", "short": "Chromatic Anklet", "link": "items.html#Chromatic Anklet"}',
	'{"long": "Ring of Very Minor Protection", "short": "Ring of Very Minor Protection", "link": "items.html#Ring of Very Minor Protection"}',
	'{"long": "Band of the Brawler", "short": "Band of the Brawler", "link": "items.html#Band of the Brawler"}',
	'{"long": "Manasteel Ingot", "short": "Manasteel Ingot", "link": "items.html#Manasteel Ingot"}',
	'{"long": "Bounce Back Sash", "short": "Bounce Back Sash", "link": "items.html#Bounce Back Sash"}',
	'{"long": "Musashi\u2019s Blades", "short": "Musashi\u2019s Blades", "link": "items.html#Musashi\u2019s Blades"}',
	'{"long": "Heedless Hammer", "short": "Heedless Hammer", "link": "items.html#Heedless Hammer"}',
	'{"long": "Lull", "short": "Lull", "link": "items.html#Lull"}',
	'{"long": "Mirror of Retaliation", "short": "Mirror of Retaliation", "link": "items.html#Mirror of Retaliation"}',
	'{"long": "Grudge Orb", "short": "Grudge Orb", "link": "items.html#Grudge Orb"}',
	'{"long": "Curse:", "short": "Curse:", "link": "items.html#Curse:"}',
	'{"long": "Boots of Sure Footing", "short": "Boots of Sure Footing", "link": "items.html#Boots of Sure Footing"}',
	'{"long": "Pass-Through Blade", "short": "Pass-Through Blade", "link": "items.html#Pass-Through Blade"}',
	'{"long": "The Markless Stiletto", "short": "Markless Stiletto", "link": "items.html#The Markless Stiletto"}',
	'{"long": "Robes of The Paranoid Mage", "short": "Robes of The Paranoid Mage", "link": "items.html#Robes of The Paranoid Mage"}',
	'{"long": "Abelheim\u2019s Instant Equipment", "short": "Abelheim\u2019s Instant Equipment", "link": "items.html#Abelheim\u2019s Instant Equipment"}',
	'{"long": "Commanding Crown", "short": "Commanding Crown", "link": "items.html#Commanding Crown"}',
	'{"long": "Ring of Eloquence", "short": "Ring of Eloquence", "link": "items.html#Ring of Eloquence"}',
	'{"long": "Eloquence.", "short": "Eloquence.", "link": "items.html#Eloquence."}',
	'{"long": "Empathy.", "short": "Empathy.", "link": "items.html#Empathy."}',
	'{"long": "Read Person.", "short": "Read Person.", "link": "items.html#Read Person."}',
	'{"long": "The Violin of Pacing", "short": "Violin of Pacing", "link": "items.html#The Violin of Pacing"}',
	'{"long": "Brand of Retribution", "short": "Brand of Retribution", "link": "items.html#Brand of Retribution"}',
	'{"long": "Thievery.", "short": "Thievery.", "link": "items.html#Thievery."}',
	'{"long": "Fraud.", "short": "Fraud.", "link": "items.html#Fraud."}',
	'{"long": "Murder.", "short": "Murder.", "link": "items.html#Murder."}',
	'{"long": "Token of Versatility", "short": "Token of Versatility", "link": "items.html#Token of Versatility"}',
	'{"long": "Contacts of Quick Reaction", "short": "Contacts of Quick Reaction", "link": "items.html#Contacts of Quick Reaction"}',
	'{"long": "Rod of Seclusion", "short": "Rod of Seclusion", "link": "items.html#Rod of Seclusion"}',
	'{"long": "The Sheikah Slate", "short": "Sheikah Slate", "link": "items.html#The Sheikah Slate"}',
	'{"long": "Sheikah Scope &amp; Map.", "short": "Sheikah Scope &amp; Map.", "link": "items.html#Sheikah Scope &amp; Map."}',
	'{"long": "Camera &amp; Sheikah Sensor.", "short": "Camera &amp; Sheikah Sensor.", "link": "items.html#Camera &amp; Sheikah Sensor."}',
	'{"long": "Adventure Log.", "short": "Adventure Log.", "link": "items.html#Adventure Log."}',
	'{"long": "Remote Bomb.", "short": "Remote Bomb.", "link": "items.html#Remote Bomb."}',
	'{"long": "Magnesis.", "short": "Magnesis.", "link": "items.html#Magnesis."}',
	'{"long": "Stasis.", "short": "Stasis.", "link": "items.html#Stasis."}',
	'{"long": "Cryonis.", "short": "Cryonis.", "link": "items.html#Cryonis."}',
	'{"long": "Spectacles of Spell Analyzation", "short": "Spectacles of Spell Analyzation", "link": "items.html#Spectacles of Spell Analyzation"}',
	'{"long": "Meteorite", "short": "Meteorite", "link": "items.html#Meteorite"}',
	'{"long": "Sword of Mercy", "short": "Sword of Mercy", "link": "items.html#Sword of Mercy"}',
	'{"long": "Sword of Judgement", "short": "Sword of Judgement", "link": "items.html#Sword of Judgement"}',
	'{"long": "Handkerchief of Cleanliness", "short": "Handkerchief of Cleanliness", "link": "items.html#Handkerchief of Cleanliness"}',
	'{"long": "Ring of Skill: Distant Strike", "short": "Ring of Skill: Distant Strike", "link": "items.html#Ring of Skill: Distant Strike"}',
	'{"long": "Void Link", "short": "Void Link", "link": "items.html#Void Link"}'
]
